/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZenohTestIndexRouteImport } from './routes/zenoh-test/index'
import { Route as ZenohBackendIndexRouteImport } from './routes/zenoh-backend/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZenohTestIndexRoute = ZenohTestIndexRouteImport.update({
  id: '/zenoh-test/',
  path: '/zenoh-test/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZenohBackendIndexRoute = ZenohBackendIndexRouteImport.update({
  id: '/zenoh-backend/',
  path: '/zenoh-backend/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/zenoh-backend/': typeof ZenohBackendIndexRoute
  '/zenoh-test/': typeof ZenohTestIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/zenoh-backend': typeof ZenohBackendIndexRoute
  '/zenoh-test': typeof ZenohTestIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/zenoh-backend/': typeof ZenohBackendIndexRoute
  '/zenoh-test/': typeof ZenohTestIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/zenoh-backend/' | '/zenoh-test/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/zenoh-backend' | '/zenoh-test'
  id: '__root__' | '/' | '/zenoh-backend/' | '/zenoh-test/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ZenohBackendIndexRoute: typeof ZenohBackendIndexRoute
  ZenohTestIndexRoute: typeof ZenohTestIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zenoh-test/': {
      id: '/zenoh-test/'
      path: '/zenoh-test'
      fullPath: '/zenoh-test/'
      preLoaderRoute: typeof ZenohTestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zenoh-backend/': {
      id: '/zenoh-backend/'
      path: '/zenoh-backend'
      fullPath: '/zenoh-backend/'
      preLoaderRoute: typeof ZenohBackendIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ZenohBackendIndexRoute: ZenohBackendIndexRoute,
  ZenohTestIndexRoute: ZenohTestIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
